name: AOC-Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install cargo-aoc
      run: cargo install cargo-aoc
    - uses: actions/checkout@v3
    - name: AOC runs
      run: cargo aoc
